### ISSUE TITLE
Paper about Lato

### ISSUE THREAD

**Issue by mariebauer** [latofonts/lato-source#22]
Dear Mr. Dziedzic, 

I am a German student writing a paper about your font Lato in a course about typography. I have chosen Lato because I really like the font and have already used it several times. Thanks to your website, I have already gathered some background information about Lato, but I would be happy if you had the time to answer me some more questions about this wonderful font you designed:
1. What exactly was your intention when you designed Lato? Why have you decided to design it in this specific way?
2. What are your feelings about this font? Does it have a special meaning to you, especially if you compare it to the other fonts you have designed?
3. Is Lato 2.0 already the final version or do you plan to develop another version of Lato?

I would be grateful if you could answer me these questions and if you could maybe provide me a picture of you so I can illustrate your biography in my paper.

Thank you in advance!

Best regards,
Marie Bauer

**Comment by typoland** [comment]
Marie, oh dear!

Lato's story is a long one. I was approached by an ad agency to help redesign the logotype for an old Polish bank. I took on the task. I liked it, and the bank boss liked it. This led to a request for a font, not just a few letters for the logo. That's what I did. It was quick. They liked it. However, from what I understand, the high bank boss was forced to change the bank's CI in a month, or he would be fired. My high boss changed immediately agencies to another one, claimed that I did a font that was "stolen from somewhere" and parted ways. The bank purchased a custom font made by a new agency, which some people in the type industry believe is stolen. 
Nevertheless, I had a brand new font. At the time, Google had just launched its GoogleFont repository. Adam Twardoch, author of the name Lato, proposed I put this font into one. The agreement was simple: I developed Lato for other scripts such as extended European glyphs, Cyrillic, Vietnam, and they would pay me some reasonable amount of money for it. After paying for a first stage, simple character set (20% of the deal), they said "sorry, we don't need more". Good. Unfortunately, the OpenFont license has already been granted to Lato. Okay. 
In a few years, Google asked me to make a font based on Lato that would replace Callibri with the same glyphs, widths, and kerning, but with a different design. This is for users who want to edit documents made with Callibri on Windows, but also on many other platforms, such as UNIX and MacOS. I said - but first I'd like to finish Lato, and then I'll make this Frankenstein font. I got their approval. Lato was made with the same glyph set as Callibri, and later, with Adam Twardoch's help, we made Carlito to replace it. Carlito is ugly, but it can be useful to some. As a result, I became a thief as I had stolen metrics from Lucas de Grot’s Callibri. Now he hates me. Okay. 
Some ad agency contacted me a few months ago about redesigning a bank's corporate font. The same bank where it began. In the tram today, Lato told me I should wear a mask. Okay. 
No more working with Lato. That was too much.
