### ISSUE TITLE
Czech characters

### ISSUE THREAD

**Issue by BlankaPi** [latofonts/lato-source#41]
We use the font on many multilingual sites and we are missing Czech characters. Do you plan to add missing letters from the czech alphabet?

**Comment by kenmcd** [comment]
I assume you are talking about the Google Fonts version of Lato.
Currently that is Lato v1.104.
That version does not have: ť, ď, ľ, and Ľ
So your only option right now is to self-host the fonts.
Lato v2.015 does have those characters.
You can download the v2.015 TTF and WOFF2 fonts here:
https://www.latofonts.com/lato-free-fonts/

Google Fonts did update to the v2 fonts briefly, but IIRC there were some metrics differences so they reverted the upgrade.
So they are not going to supply the v2 fonts.

The v3 fonts under development in this repo will also have those characters.
Unknown when that will happen.

**Comment by BlankaPi** [comment]
Thank You very much. That explained and helped a lot.
