### ISSUE TITLE
4/5 character ⅘ incorrectly displays as 4/8

### ISSUE THREAD

**Issue by q00u** [latofonts/lato-source#49]
Lato's 4/5 character, `⅘`, incorrectly displays as `4/8`. Unicode has no `4/8` character. Lato is the only typeface that has this mistake.

![Screenshot from 2024-01-11 07-14-45](https://github.com/latofonts/lato-source/assets/892302/cdccbef1-f278-459b-8858-1c467857aaf3)

**Comment by kenmcd** [comment]
That error is in v2.015.
It has been fixed in v3.

**Comment by q00u** [comment]
Good to know! Looks like Slack is using a very old version then.

**Comment by mck182** [comment]
hey @kenmcd, where does one get the v3?
all the listed downloads seem to only have
the v2 with this bug.

does the v3 need to be built from the sources?
