### ISSUE TITLE
Long hasn’t your website updated

### ISSUE THREAD

**Issue by tanukihee** [latofonts/lato-source#5]
The most up-to-date release version in your [website](http://www.latofonts.com/) is `2.015`, which is far out of date. It would be better if your website could be updated.

**Comment by hpfr** [comment]
Note that the `3.001-dev` and `3.002-dev` releases have the `dev` suffix. This means the third major version is a work in progress, and thus `2.015` is up-to-date.

**Comment by twardoch** [comment]
The 3.x series is not quite yet recommended for general usage. It’s generally fine but is not yet thoroughly tested, and some new glyphs are not yet finished.

**Comment by tanukihee** [comment]
I see. Thanks
